#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
nitrogen --restore &
~/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Mice bindings
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Telegram-desktop state=floating
bspc rule -a Jetbrains-toolbox state=floating
setxkbmap -option grp:alt_shift_toggle us,ru
kitty &
