#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
nitrogen --restore &

bspc monitor -d 1 2 3 4 5
bspc config border_width 1
bspc config normal_border_color "#F5E0DC"
bspc config active_border_color "#EBA0AC"
bspc config window_gap 12

bspc config split_ratio          1
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Mice bindings
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Telegram-desktop state=floating
bspc rule -a Jetbrains-toolbox state=floating
setxkbmap -option grp:alt_shift_toggle us,ru
