#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
dunst &
picom &
polybar &
nitrogen --restore
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6
bspc config border_width 1
bspc config window_gap 12

bspc config split_ratio          1
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Mice bindings
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Telegram-desktop state=floating
bspc rule -a Jetbrains-toolbox state=floating
bspc rule -a jetbrains-idea-ce desktop=^3  # intellij 'did you know' popup
bspc rule -a jetbrains-idea-c desktop=^3  # the rest of intellij
setxkbmap -option grp:alt_shift_toggle us,ru
